### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-css-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://youthful-hose.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/css-intro/1) criteria:
- [x] Include at least one instance of the `margin` property.
- [x] Include at least one instance of the `padding` property.
- [x] Include at least one instance of the `border` property.
- [x] Include at least one instance of the `color` property.
- [x] Include at least one instance of the `background` property.
- [x] Include at least one instance of the `font-size` property.
- [x] Include at least one instance of the `line-height` property.
- [x] All properties must have a visible effect.
- [x] Return no errors (warnings are OK) when the HTML document is uploaded to the [W3C Markup Validation Service](http://validator.w3.org/#validate_by_upload)
- [x] Return no errors or warnings when contents of your CSS are pasted into [CSS Lint](http://csslint.net/)

**Comment by chrisvfritz** [comment]
Same comments as [on this project](https://github.com/ackleyd1/codelab-html-intro/issues/1#issuecomment-170947973), but now I'll focus more on the content of the CSS. First, it looks very good so far. I can tell you're not a beginner to CSS - especially from the left and right `margin` `auto` to center the image! 

The only issue I see is relatively minor:

### Unitless `line-height`s

While a percentage for `line-height` _is_ technically valid, it's generally recommended to use the unitless equivalent instead. So in this case, instead of `200%`, we'd use `2`. The reason can be a little complicated to beginners of CSS, but the gist is the unitless version will always behave as you expect - the percent version will _not_. Here's the full, technically explanation from [CSS Tricks](https://css-tricks.com/almanac/properties/l/line-height/):

> Unitless line heights are recommended due to the fact that child elements will inherit the raw number value, rather than the computed value. With this, child elements can compute their line heights based on their computed font size, rather than inheriting an arbitrary value from a parent that is more likely to need overriding.

---

Once again, let me know when this is updated and I'll take another look. Oh - and one more thing I have to ask out or curiosity. I noticed you're an SSBM fan. Do you also play competitively yourself?

**Comment by ackleyd1** [comment]
I updated this one as well and I have one question about centering elements. I found out how to do that image one by looking it up but I think the link that taught CSS suggested this trick [here.](https://github.com/ackleyd1/codelab-css-intro/blob/master/index.html#L33) Why doesn't this center my "Twitter" link? And yes I am a huge SSBM fan hahah, I'd say my competitive career is still ahead of me. I haven't been to any big tournaments but I have been to some small events at MSU.

**Comment by ackleyd1** [comment]
Ignore my epic fail at the markdown styling

**Comment by chrisvfritz** [comment]
Hey, the fact that you even know what Markdown _is_ and almost got it right is pretty solid at this point. :+1: 

As for centering, it's unfortunately a little more complicated than it should be. _Fortunately_, there's only one thing that's important to understand before learning how to center everything. That is **every element has a display type that affects how properties work on them**. 

`margin-left: auto;`margin-right: auto;`has the same effect as`margin: 0 auto`(with the addition of setting the top and bottom margin to 0), but it works on the image because you've added`display: block`. That's the context that`margin: 0 auto` will center things in.

Your `a` element on the other hand, is `display: inline` (that's the default for anchor elements). This display type is fantastic when you want an element to fit in as a natural part of a sentence, but not when it's standing on its own and you want to center it. As a solution here, you could either change the `a`'s display type _or_ wrap it in something like a `p` (which is `display: block`) and apply `text-align: center` to the containing paragraph.

So now that you know display types exist and that they affect the strategies you'll use for alignment, I recommend reading [_Centering in CSS: A Complete Guide_](https://css-tricks.com/centering-css-complete-guide/), which is a very thorough resource on how to center any kind of element. Let me know if that helps!

I'll also wait on approving this project until we get that centered, so it doesn't fall off our radar.

**Comment by ackleyd1** [comment]
Centered twitter link

**Comment by chrisvfritz** [comment]
Looks great! :tada: :shipit:
